# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_streamer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14video_streamer.proto\x12\x13\x64roniada_vid_stream\",\n\rStreamRequest\x12\x0b\n\x03\x63\x61p\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\x15\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32]\n\rVideoStreamer\x12L\n\x06Stream\x12\".droniada_vid_stream.StreamRequest\x1a\x1a.droniada_vid_stream.Image\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_streamer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STREAMREQUEST._serialized_start=45
  _STREAMREQUEST._serialized_end=89
  _IMAGE._serialized_start=91
  _IMAGE._serialized_end=112
  _VIDEOSTREAMER._serialized_start=114
  _VIDEOSTREAMER._serialized_end=207
# @@protoc_insertion_point(module_scope)
